---
title: "Data quality and plausibility check"
subtitle: "`r strings['dataset.name.short']`"
output: html_document
---

<style>
.tocify-subheader {
  font-size: 0.7em;
}
.tocify-item {
  font-size: 0.85em;
  padding-left: 25px;
  text-indent: 0;
}
</style>

```{r logo, echo=FALSE}
htmltools::img(src = knitr::image_uri("resources/Logo_Reach_RGB_1.png"), 
               alt = "REACH logo",
               style = 'position:absolute; top:0; right:0; padding:0; margin:20; width:250px')
```



```{r setup, include=FALSE}
  knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
  options(scipen = 999)
  rm(list=ls()[!ls() %in% c( "strings","params")])
  
  source("src/init_quality_checks.R")
  source("src/functions_quality_check_plaus_report.R")
  
```

# {.tabset}
## Introduction
### Feedback

Feedback on improvements to this product can be done through reaching out to: ???

## FSL

```{r, echo=FALSE, warning=FALSE,include=FALSE}

## make sure to add the scores
main <- data.list$main %>% 
  dplyr::mutate_at(vars(fcs_cereal,fcs_legumes,fcs_dairy,fcs_meat,fcs_veg,fcs_fruit,fcs_oil,fcs_sugar),as.numeric) %>%
  dplyr::mutate(fcs_weight_cereal1 = ifelse(is.na(fcs_cereal), NA, fcs_cereal * 2),
                fcs_weight_legume2 = ifelse(is.na(fcs_legumes), NA, fcs_legumes * 3),
                fcs_weight_dairy3 = ifelse(is.na(fcs_dairy), NA, fcs_dairy * 4),
                fcs_weight_meat4 = ifelse(is.na(fcs_meat), NA, fcs_meat * 4),
                fcs_weight_veg5 = ifelse(is.na(fcs_veg), NA, fcs_veg * 1),
                fcs_weight_fruit6 = ifelse(is.na(fcs_fruit), NA, fcs_fruit * 1),
                fcs_weight_oil7 = ifelse(is.na(fcs_oil), NA, fcs_oil * 0.5),
                fcs_weight_sugar8 = ifelse(is.na(fcs_sugar), NA, fcs_sugar * 0.5)) %>% 
  dplyr::mutate(fcs_score = fcs_weight_cereal1 + fcs_weight_legume2 + fcs_weight_dairy3 + 
                  fcs_weight_meat4 + fcs_weight_veg5 + fcs_weight_fruit6 + fcs_weight_oil7 + fcs_weight_sugar8,
                fcs_cat = dplyr::case_when(is.na(fcs_score) ~ NA_character_,
                                           fcs_score < 21.5 ~ "Poor",
                                           fcs_score <= 35 ~ "Borderline",
                                           fcs_score > 35 & fcs_score < 200 ~ "Acceptable",
                                           TRUE ~ NA_character_)) %>%
  dplyr::mutate_at(vars(rcsi_lessquality,rcsi_borrow,rcsi_mealsize,rcsi_mealadult,rcsi_mealnb),as.numeric) %>% 
  addindicators::add_rcsi(rCSILessQlty = "rcsi_lessquality",
                          rCSIBorrow = "rcsi_borrow",
                          rCSIMealSize = "rcsi_mealsize",
                          rCSIMealAdult = "rcsi_mealadult",
                          rCSIMealNb = "rcsi_mealnb") %>% 
  mutate_at(vars(hhs_lack_food,hhs_sleep_nofood,hhs_wholedaynight_nofood),~ifelse(. %in% c('dk','dwta'),'no',.)) %>% 
  addindicators::add_hhs(hhs_nofoodhh_1 = "hhs_lack_food",
                         hhs_nofoodhh_1a = "hhs_lack_food_freq",
                         hhs_sleephungry_2 = "hhs_sleep_nofood",
                         hhs_sleephungry_2a = "hhs_sleep_nofood_freq",
                         hhs_alldaynight_3 = "hhs_wholedaynight_nofood",
                         hhs_alldaynight_3a = "hhs_wholedaynight_nofood_freq",
                         yes_answer = "yes", no_answer = "no", rarely_answer = "rarely", 
  sometimes_answer = "sometimes", often_answer = "often")
# %>% 
#   addindicators::add_lcsi(lcsi_stress_vars =  c("lcsi_stress1","lcsi_stress2","lcsi_stress3","lcsi_stress4"),
#                           lcsi_crisis_vars = c("lcsi_crisis1","lcsi_crisis2","lcsi_crisis3"),
#                           lcsi_emergency_vars = c("lcsi_emergency1","lcsi_emergency2","lcsi_emergency3")) %>% 
#   addindicators::add_fcm_phase(hhs_categories_little = "No or Little")

### FOR ETHIOPIA

# num_children <- data.list$main %>% 
#   mutate(is_child = ifelse(as.numeric(ind_age) < 6, 1, 0)) %>% 
#   group_by(uuid) %>% 
#   summarise(num_children = sum(is_child))
# 
# main <- main %>% 
#   left_join(num_children, by="uuid")

### FOR MSNA AFGH
main <- main %>% 
  mutate(num_children = rowSums(across(c(children_under_1_total,children_1_5_total), .fns = as.numeric), na.rm = T))

```

## Ethiopia 
```{r}
flag <- check_fs_flags(main)
```

```{r}
result <- create_fsl_quality_report_test(flag)
result_enum <- create_fsl_quality_report_test(flag, grouping = "enumerator")
result_short <- create_fsl_quality_report_test(flag, short_report = T)
result_enum_short <- create_fsl_quality_report_test(flag, grouping = "enumerator", short_report = T)

sheets <- list("long_result_all" = result,
               "long_result_enum" = result_enum,
               "short_result_all" = result_short,
               "short_result_enum" = result_enum_short,
               "flag" = flag)

write_xlsx(sheets, "output/quality_report/quality_plausibility_report_afg_msna.xlsx")
```

```{r}

```
